import Foundation

nonisolated struct LocalNotificationActionOptions: OptionSet, Hashable, Codable, Sendable { let rawValue: UInt; static let foreground = Self(rawValue: 1 << 0); static let destructive = Self(rawValue: 1 << 1); static let authenticationRequired = Self(rawValue: 1 << 2); static let allowed: Self = [.foreground, .destructive, .authenticationRequired]; init(rawValue: UInt) { self.rawValue = rawValue } }
nonisolated struct LocalNotificationButtonAction: Hashable, Codable, Sendable { let id: LocalNotificationActionID; let title: String; let options: LocalNotificationActionOptions; let deepLink: URL?; init(id: LocalNotificationActionID, title: String, options: LocalNotificationActionOptions = [], deepLink: URL? = nil) { self.id = id; self.title = title; self.options = options; self.deepLink = deepLink } }
nonisolated struct LocalNotificationTextInputAction: Hashable, Codable, Sendable { let id: LocalNotificationActionID; let title: String; let options: LocalNotificationActionOptions; let deepLink: URL?; let textInputButtonTitle: String; let textInputPlaceholder: String?; init(id: LocalNotificationActionID, title: String, options: LocalNotificationActionOptions = [], deepLink: URL? = nil, textInputButtonTitle: String, textInputPlaceholder: String? = nil) { self.id = id; self.title = title; self.options = options; self.deepLink = deepLink; self.textInputButtonTitle = textInputButtonTitle; self.textInputPlaceholder = textInputPlaceholder } }
nonisolated enum LocalNotificationAction: Hashable, Codable, Sendable { case button(LocalNotificationButtonAction); case textInput(LocalNotificationTextInputAction); var id: LocalNotificationActionID { switch self { case let .button(action): action.id; case let .textInput(action): action.id } } }
nonisolated struct LocalNotificationCategory: Hashable, Codable, Sendable {
    let id: LocalNotificationCategoryID; let actions: [LocalNotificationAction]; let hiddenPreviewsBodyPlaceholder: String?; let categorySummaryFormat: String?; let hiddenPreviewsShowTitle: Bool; let hiddenPreviewsShowSubtitle: Bool; let reportsDismissal: Bool
    init(id: LocalNotificationCategoryID, actions: [LocalNotificationAction] = [], hiddenPreviewsBodyPlaceholder: String? = nil, categorySummaryFormat: String? = nil, hiddenPreviewsShowTitle: Bool = false, hiddenPreviewsShowSubtitle: Bool = false, reportsDismissal: Bool = false) { self.id = id; self.actions = actions; self.hiddenPreviewsBodyPlaceholder = hiddenPreviewsBodyPlaceholder; self.categorySummaryFormat = categorySummaryFormat; self.hiddenPreviewsShowTitle = hiddenPreviewsShowTitle; self.hiddenPreviewsShowSubtitle = hiddenPreviewsShowSubtitle; self.reportsDismissal = reportsDismissal }
}
